[package]
name = "diffie-hellman"
version = "0.1.0"
authors = ["Kieran Wood <kieran@canadiancoding.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"